### ISSUE TITLE
Patch Path

### ISSUE THREAD

**Issue by MattBixley** [nesi/eri-easyconfigs#1]
There is one feature in Mahuika EASYBUILD which is not mimicked on eRI is the patch path lookup. eRI only looks for /src/ directory for patches which means it is in a completely separate directory from easyconfigs. This used to be the case in Mahuika early  on and we changed it in a way where patches can go on the same path as easyConfigs.
Otherwise, upstream repo will not have the patched by default

**Comment by DininduSenanayake** [comment]
All sorted now. In fact, it was a to do with mis-configuration on my local  than an issue with the global settings.
